# Generated by Django 5.0.6 on 2024-07-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='PROJECT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('disc', models.CharField(max_length=100)),
            ],
        ),
    ]
