# Generated by Django 5.0.6 on 2024-07-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='EDUCATION',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=50)),
                ('degree', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=20)),
            ],
        ),
    ]
